apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "haproxy.fullname" . }}-config
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
data:
  haproxy.cfg: |
    {{ .Values.haproxy.config | nindent 4 }}
    
    {{- if .Values.configMap.additionalConfig }}
    # Additional configuration from values
    {{ .Values.configMap.additionalConfig | nindent 4 }}
    {{- end }} 