apiVersion: v1
kind: Service
metadata:
  name: sim-backend
  labels:
    {{- include "sim-backend.common-labels" $ | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    name: simapi
  - port: 3002
    targetPort: 3002
    nodePort: 30021
    name: reportapi
  - port: 3003
    targetPort: 3003
    nodePort: 30031
    name: testapi
  selector:
    {{- include "sim-backend.common-labels" $ | nindent 6 }}
