{{- if .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault.fullname" . }}-init-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
type: Opaque
data:
  # Secret shares and threshold configuration for auto-init
  secret-shares: {{ .Values.vault.init.secretShares | toString | b64enc | quote }}
  secret-threshold: {{ .Values.vault.init.secretThreshold | toString | b64enc | quote }}
  
  # Additional configuration for auto-init
  vault-init-config: {{ printf `{
    "secret_shares": %d,
    "secret_threshold": %d,
    "stored_shares": 1,
    "recovery_shares": 1,
    "recovery_threshold": 1
  }` .Values.vault.init.secretShares .Values.vault.init.secretThreshold | b64enc | quote }}
{{- end }}