apiVersion: v1
kind: Service
metadata:
  name: {{ include "sim-ui.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort | default (30600) }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "sim-ui.name" . }}